// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type RestaurantTableRequest = {
    name: string;
    capacity: number;
};

export type RestaurantTableResponse = {
    id?: number;
    name?: string;
    occupied?: boolean;
    qrUrl?: string;
    capacity?: number;
    status?: boolean;
};

export type SupplierRequest = {
    nombre: string;
    ruc: string;
    contacto: string;
    email: string;
    telefono: string;
};

export type SupplierResponse = {
    id?: number;
    nombre?: string;
    ruc?: string;
    contacto?: string;
    email?: string;
    telefono?: string;
    estado?: boolean;
};

export type ProductRequest = {
    name: string;
    description: string;
    price: number;
    categoryId: number;
};

export type ProductResponse = {
    id?: number;
    name?: string;
    description?: string;
    price?: number;
    categoryId?: number;
    categoryName?: string;
    status?: boolean;
    imageUrl?: string;
};

export type ProductInventoryRequest = {
    name: string;
    description?: string;
    categoryId: number;
    unitary: string;
};

export type ProductInventoryResponse = {
    id?: number;
    name?: string;
    description?: string;
    categoryId?: number;
    categoryName?: string;
    status?: boolean;
    unitary?: string;
};

export type EmployeeRequest = {
    name: string;
    lastname: string;
    documentType: string;
    documentNumber: string;
    position: string;
    contractType: string;
    weeklyHours: number;
    hourlyWage: number;
};

export type EmployeeResponse = {
    id?: number;
    name?: string;
    lastname?: string;
    documentType?: string;
    documentNumber?: string;
    status?: boolean;
    position?: string;
    contractType?: string;
    weeklyHours?: number;
    hourlyWage?: number;
};

export type CategoryRequest = {
    name: string;
    description: string;
};

export type CategoryResponse = {
    id: number;
    name: string;
    description: string;
    status: boolean;
};

export type CategoryInventoryRequest = {
    name: string;
    description?: string;
};

export type CategoryInventoryResponse = {
    id: number;
    name: string;
    description?: string;
    status: boolean;
};

export type CreateUserDto = {
    username: string;
    password: string;
    roleId: number;
    status?: boolean;
    employeeId: number;
};

export type UserResponse = {
    id?: number;
    email?: string;
    role?: 'ADMIN' | 'MOZO' | 'CAJERO' | 'COCINERO' | 'DELIVERY';
    status?: boolean;
    personId?: number;
    personName?: string;
    personLastname?: string;
};

export type SaleRequest = {
    orderId: number;
    metodo: 'EFECTIVO' | 'TARJETA' | 'YAPE' | 'MERCADO_PAGO';
};

export type SaleResponse = {
    id?: number;
    codigo?: string;
    fecha?: string;
    metodo?: 'EFECTIVO' | 'TARJETA' | 'YAPE' | 'MERCADO_PAGO';
    monto?: number;
    orderId?: number;
    orderCode?: string;
};

export type OrderItemRequest = {
    productId: number;
    quantity: number;
};

export type OrderRequest = {
    type: string;
    tableId?: number;
    customerName?: string;
    customerPhone?: string;
    customerEmail?: string;
    customerDni?: string;
    location?: string;
    paymentMethod?: string;
    items: Array<OrderItemRequest>;
};

export type OrderItemResponse = {
    id?: number;
    productId?: number;
    productName?: string;
    priceUnitary?: number;
    quantity?: number;
    subtotal?: number;
    productImageUrl?: string;
};

export type OrderResponse = {
    id?: number;
    code?: string;
    status?: 'PENDIENTE' | 'PREPARANDO' | 'LISTO' | 'CAMINO' | 'ENTREGADO' | 'CANCELADO';
    type?: 'SALON' | 'DELIVERY';
    tableId?: number;
    tableName?: string;
    totalPrice?: number;
    customerName?: string;
    customerPhone?: string;
    customerEmail?: string;
    customerDni?: string;
    location?: string;
    paymentMethod?: string;
    createdAt?: string;
    items?: Array<OrderItemResponse>;
};

export type MovementInventoryRequest = {
    productInventoryId: number;
    tipo: 'ENTRADA' | 'SALIDA';
    cantidad: number;
    razon: string;
};

export type MovementInventoryResponse = {
    id?: number;
    productInventoryId?: number;
    productInventoryName?: string;
    fecha?: string;
    tipo?: 'ENTRADA' | 'SALIDA';
    cantidad?: number;
    razon?: string;
};

export type EmployeeUserRequest = {
    name: string;
    lastname: string;
    documentType: string;
    documentNumber: string;
    position: string;
    contractType: string;
    weeklyHours: number;
    hourlyWage: number;
    user: UserRequest;
};

export type UserRequest = {
    email: string;
    password: string;
    role: 'ADMIN' | 'MOZO' | 'CAJERO' | 'COCINERO' | 'DELIVERY';
};

export type CashBoxRequest = {
    name: string;
    openingAmount: number;
};

export type CashBoxResponse = {
    id?: number;
    name?: string;
    openingAmount?: number;
    currentBalance?: number;
    collectedSales?: number;
    openingTime?: string;
    closingTime?: string;
    status?: 'ABIERTA' | 'CERRADA';
};

export type MovementCashboxRequest = {
    cashBoxId: number;
    codigoPedidos?: string;
    tipoComprobante?: string;
    descripcion: string;
    tipo: 'INGRESO' | 'EGRESO';
    monto: number;
};

export type MovementCashboxResponse = {
    id?: number;
    cashBoxId?: number;
    dia?: string;
    hora?: string;
    codigoPedidos?: string;
    tipoComprobante?: string;
    descripcion?: string;
    tipo?: 'INGRESO' | 'EGRESO';
    monto?: number;
};

export type AuthRequest = {
    email: string;
    password: string;
};

export type PageUserResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<UserResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    paged?: boolean;
    pageNumber?: number;
    pageSize?: number;
    unpaged?: boolean;
};

export type SortObject = {
    empty?: boolean;
    sorted?: boolean;
    unsorted?: boolean;
};

export type PageRestaurantTableResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<RestaurantTableResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageSupplierResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<SupplierResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageSaleResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<SaleResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type SaleSummaryDto = {
    id?: number;
    cliente?: string;
    fecha?: string;
    total?: number;
    estado?: string;
    metodoPago?: string;
    orderId?: number;
};

export type ProductTopDto = {
    id?: number;
    productName?: string;
    quantity?: number;
    totalCollected?: number;
};

export type PageProductResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<ProductResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageProductInventoryResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<ProductInventoryResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageOrderResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<OrderResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type OrderDeliveryDto = {
    id?: number;
    code?: string;
    status?: string;
    customerName?: string;
    customerPhone?: string;
    customerEmail?: string;
    customerDni?: string;
    address?: string;
    totalPrice?: number;
    time?: string;
    paymentMethod?: string;
    products?: Array<OrderDeliveryItemDto>;
};

export type OrderDeliveryItemDto = {
    id?: number;
    name?: string;
    priceUnitary?: number;
    quantity?: number;
};

export type PageMovementInventoryResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<MovementInventoryResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageEmployeeResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<EmployeeResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageCategoryResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<CategoryResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageCategoryInventoryResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<CategoryInventoryResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageCashBoxResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<CashBoxResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type PageMovementCashboxResponse = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<MovementCashboxResponse>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
};

export type GetTableByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}';
};

export type GetTableByIdResponses = {
    /**
     * OK
     */
    200: RestaurantTableResponse;
};

export type GetTableByIdResponse = GetTableByIdResponses[keyof GetTableByIdResponses];

export type UpdateTableData = {
    body: RestaurantTableRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}';
};

export type UpdateTableResponses = {
    /**
     * OK
     */
    200: RestaurantTableResponse;
};

export type UpdateTableResponse = UpdateTableResponses[keyof UpdateTableResponses];

export type GetSupplierByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}';
};

export type GetSupplierByIdResponses = {
    /**
     * OK
     */
    200: SupplierResponse;
};

export type GetSupplierByIdResponse = GetSupplierByIdResponses[keyof GetSupplierByIdResponses];

export type UpdateSupplierData = {
    body: SupplierRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}';
};

export type UpdateSupplierResponses = {
    /**
     * OK
     */
    200: SupplierResponse;
};

export type UpdateSupplierResponse = UpdateSupplierResponses[keyof UpdateSupplierResponses];

export type GetProductByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetProductByIdResponses = {
    /**
     * OK
     */
    200: ProductResponse;
};

export type GetProductByIdResponse = GetProductByIdResponses[keyof GetProductByIdResponses];

export type UpdateProductData = {
    body: ProductRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type UpdateProductResponses = {
    /**
     * OK
     */
    200: ProductResponse;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type GetProductInventoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products-inventory/{id}';
};

export type GetProductInventoryByIdResponses = {
    /**
     * OK
     */
    200: ProductInventoryResponse;
};

export type GetProductInventoryByIdResponse = GetProductInventoryByIdResponses[keyof GetProductInventoryByIdResponses];

export type UpdateProductInventoryData = {
    body: ProductInventoryRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products-inventory/{id}';
};

export type UpdateProductInventoryResponses = {
    /**
     * OK
     */
    200: ProductInventoryResponse;
};

export type UpdateProductInventoryResponse = UpdateProductInventoryResponses[keyof UpdateProductInventoryResponses];

export type GetEmployeeByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/employees/{id}';
};

export type GetEmployeeByIdResponses = {
    /**
     * OK
     */
    200: EmployeeResponse;
};

export type GetEmployeeByIdResponse = GetEmployeeByIdResponses[keyof GetEmployeeByIdResponses];

export type UpdateEmployeeData = {
    body: EmployeeRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/employees/{id}';
};

export type UpdateEmployeeResponses = {
    /**
     * OK
     */
    200: EmployeeResponse;
};

export type UpdateEmployeeResponse = UpdateEmployeeResponses[keyof UpdateEmployeeResponses];

export type GetCategoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type GetCategoryByIdResponses = {
    /**
     * OK
     */
    200: CategoryResponse;
};

export type GetCategoryByIdResponse = GetCategoryByIdResponses[keyof GetCategoryByIdResponses];

export type UpdateCategoryData = {
    body: CategoryRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * OK
     */
    200: CategoryResponse;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetCategoryInventoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories-inventory/{id}';
};

export type GetCategoryInventoryByIdResponses = {
    /**
     * OK
     */
    200: CategoryInventoryResponse;
};

export type GetCategoryInventoryByIdResponse = GetCategoryInventoryByIdResponses[keyof GetCategoryInventoryByIdResponses];

export type UpdateCategoryInventoryData = {
    body: CategoryInventoryRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories-inventory/{id}';
};

export type UpdateCategoryInventoryResponses = {
    /**
     * OK
     */
    200: CategoryInventoryResponse;
};

export type UpdateCategoryInventoryResponse = UpdateCategoryInventoryResponses[keyof UpdateCategoryInventoryResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<UserResponse>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserResponses = {
    /**
     * Created
     */
    201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type GetAllTablesResponses = {
    /**
     * OK
     */
    200: Array<RestaurantTableResponse>;
};

export type GetAllTablesResponse = GetAllTablesResponses[keyof GetAllTablesResponses];

export type CreateTableData = {
    body: RestaurantTableRequest;
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type CreateTableResponses = {
    /**
     * Created
     */
    201: RestaurantTableResponse;
};

export type CreateTableResponse = CreateTableResponses[keyof CreateTableResponses];

export type GetAllSuppliersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/suppliers';
};

export type GetAllSuppliersResponses = {
    /**
     * OK
     */
    200: Array<SupplierResponse>;
};

export type GetAllSuppliersResponse = GetAllSuppliersResponses[keyof GetAllSuppliersResponses];

export type CreateSupplierData = {
    body: SupplierRequest;
    path?: never;
    query?: never;
    url: '/api/suppliers';
};

export type CreateSupplierResponses = {
    /**
     * Created
     */
    201: SupplierResponse;
};

export type CreateSupplierResponse = CreateSupplierResponses[keyof CreateSupplierResponses];

export type GetSalesData = {
    body?: never;
    path?: never;
    query?: {
        metodo?: 'EFECTIVO' | 'TARJETA' | 'YAPE' | 'MERCADO_PAGO';
        startDate?: string;
        endDate?: string;
        page?: number;
        size?: number;
    };
    url: '/api/sales';
};

export type GetSalesResponses = {
    /**
     * OK
     */
    200: PageSaleResponse;
};

export type GetSalesResponse = GetSalesResponses[keyof GetSalesResponses];

export type CreateSaleData = {
    body: SaleRequest;
    path?: never;
    query?: never;
    url: '/api/sales';
};

export type CreateSaleResponses = {
    /**
     * Created
     */
    201: SaleResponse;
};

export type CreateSaleResponse = CreateSaleResponses[keyof CreateSaleResponses];

export type GetAllProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type GetAllProductsResponses = {
    /**
     * OK
     */
    200: Array<ProductResponse>;
};

export type GetAllProductsResponse = GetAllProductsResponses[keyof GetAllProductsResponses];

export type CreateProductData = {
    body: ProductRequest;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type CreateProductResponses = {
    /**
     * Created
     */
    201: ProductResponse;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type GetAllProductsInventoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/products-inventory';
};

export type GetAllProductsInventoryResponses = {
    /**
     * OK
     */
    200: Array<ProductInventoryResponse>;
};

export type GetAllProductsInventoryResponse = GetAllProductsInventoryResponses[keyof GetAllProductsInventoryResponses];

export type CreateProductInventoryData = {
    body: ProductInventoryRequest;
    path?: never;
    query?: never;
    url: '/api/products-inventory';
};

export type CreateProductInventoryResponses = {
    /**
     * Created
     */
    201: ProductInventoryResponse;
};

export type CreateProductInventoryResponse = CreateProductInventoryResponses[keyof CreateProductInventoryResponses];

export type GetOrdersData = {
    body?: never;
    path?: never;
    query?: {
        type?: 'SALON' | 'DELIVERY';
        status?: 'PENDIENTE' | 'PREPARANDO' | 'LISTO' | 'CAMINO' | 'ENTREGADO' | 'CANCELADO';
        page?: number;
        size?: number;
    };
    url: '/api/orders';
};

export type GetOrdersResponses = {
    /**
     * OK
     */
    200: PageOrderResponse;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type CreateOrderData = {
    body: OrderRequest;
    path?: never;
    query?: never;
    url: '/api/orders';
};

export type CreateOrderResponses = {
    /**
     * Created
     */
    201: OrderResponse;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type GetMovementsData = {
    body?: never;
    path?: never;
    query?: {
        productId?: number;
        tipo?: 'ENTRADA' | 'SALIDA';
        startDate?: string;
        endDate?: string;
        page?: number;
        size?: number;
    };
    url: '/api/inventory-movements';
};

export type GetMovementsResponses = {
    /**
     * OK
     */
    200: PageMovementInventoryResponse;
};

export type GetMovementsResponse = GetMovementsResponses[keyof GetMovementsResponses];

export type AddMovementData = {
    body: MovementInventoryRequest;
    path?: never;
    query?: never;
    url: '/api/inventory-movements';
};

export type AddMovementResponses = {
    /**
     * Created
     */
    201: MovementInventoryResponse;
};

export type AddMovementResponse = AddMovementResponses[keyof AddMovementResponses];

export type GetAllEmployeesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type GetAllEmployeesResponses = {
    /**
     * OK
     */
    200: Array<EmployeeResponse>;
};

export type GetAllEmployeesResponse = GetAllEmployeesResponses[keyof GetAllEmployeesResponses];

export type CreateEmployeeData = {
    body: EmployeeRequest;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type CreateEmployeeResponses = {
    /**
     * Created
     */
    201: EmployeeResponse;
};

export type CreateEmployeeResponse = CreateEmployeeResponses[keyof CreateEmployeeResponses];

export type CreateEmployeeWithUserData = {
    body: EmployeeUserRequest;
    path?: never;
    query?: never;
    url: '/api/employees/with-user';
};

export type CreateEmployeeWithUserResponses = {
    /**
     * Created
     */
    201: EmployeeResponse;
};

export type CreateEmployeeWithUserResponse = CreateEmployeeWithUserResponses[keyof CreateEmployeeWithUserResponses];

export type GetAllCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type GetAllCategoriesResponses = {
    /**
     * OK
     */
    200: Array<CategoryResponse>;
};

export type GetAllCategoriesResponse = GetAllCategoriesResponses[keyof GetAllCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryRequest;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type CreateCategoryResponses = {
    /**
     * Created
     */
    201: CategoryResponse;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type GetAllCategoriesInventoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories-inventory';
};

export type GetAllCategoriesInventoryResponses = {
    /**
     * OK
     */
    200: Array<CategoryInventoryResponse>;
};

export type GetAllCategoriesInventoryResponse = GetAllCategoriesInventoryResponses[keyof GetAllCategoriesInventoryResponses];

export type CreateCategoryInventoryData = {
    body: CategoryInventoryRequest;
    path?: never;
    query?: never;
    url: '/api/categories-inventory';
};

export type CreateCategoryInventoryResponses = {
    /**
     * Created
     */
    201: CategoryInventoryResponse;
};

export type CreateCategoryInventoryResponse = CreateCategoryInventoryResponses[keyof CreateCategoryInventoryResponses];

export type GetCashBoxesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: 'ABIERTA' | 'CERRADA';
        startDate?: string;
        endDate?: string;
        page?: number;
        size?: number;
    };
    url: '/api/cashboxes';
};

export type GetCashBoxesResponses = {
    /**
     * OK
     */
    200: PageCashBoxResponse;
};

export type GetCashBoxesResponse = GetCashBoxesResponses[keyof GetCashBoxesResponses];

export type OpenCashBoxData = {
    body: CashBoxRequest;
    path?: never;
    query?: never;
    url: '/api/cashboxes';
};

export type OpenCashBoxResponses = {
    /**
     * Created
     */
    201: CashBoxResponse;
};

export type OpenCashBoxResponse = OpenCashBoxResponses[keyof OpenCashBoxResponses];

export type AddMovement1Data = {
    body: MovementCashboxRequest;
    path?: never;
    query?: never;
    url: '/api/cashboxes/movements';
};

export type AddMovement1Responses = {
    /**
     * Created
     */
    201: MovementCashboxResponse;
};

export type AddMovement1Response = AddMovement1Responses[keyof AddMovement1Responses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: AuthRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type OccupyTableData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}/occupy';
};

export type OccupyTableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FreeTableData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}/free';
};

export type FreeTableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateTableData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}/deactivate';
};

export type DeactivateTableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateTableData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tables/{id}/activate';
};

export type ActivateTableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateSupplierData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}/deactivate';
};

export type DeactivateSupplierResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateSupplierData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}/activate';
};

export type ActivateSupplierResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateProductData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/deactivate';
};

export type DeactivateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateProductData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}/activate';
};

export type ActivateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateProductInventoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products-inventory/{id}/deactivate';
};

export type DeactivateProductInventoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateProductInventoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products-inventory/{id}/activate';
};

export type ActivateProductInventoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateOrderStatusData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        status: 'PENDIENTE' | 'PREPARANDO' | 'LISTO' | 'CAMINO' | 'ENTREGADO' | 'CANCELADO';
    };
    url: '/api/orders/{id}/status';
};

export type UpdateOrderStatusResponses = {
    /**
     * OK
     */
    200: OrderResponse;
};

export type UpdateOrderStatusResponse = UpdateOrderStatusResponses[keyof UpdateOrderStatusResponses];

export type DeactivateEmployeeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/employees/{id}/deactivate';
};

export type DeactivateEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateEmployeeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/employees/{id}/activate';
};

export type ActivateEmployeeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}/deactivate';
};

export type DeactivateCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}/activate';
};

export type ActivateCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeactivateCategoryInventoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories-inventory/{id}/deactivate';
};

export type DeactivateCategoryInventoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateCategoryInventoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories-inventory/{id}/activate';
};

export type ActivateCategoryInventoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CloseCashBoxData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cashboxes/{id}/close';
};

export type CloseCashBoxResponses = {
    /**
     * OK
     */
    200: CashBoxResponse;
};

export type CloseCashBoxResponse = CloseCashBoxResponses[keyof CloseCashBoxResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type SearchUsersData = {
    body?: never;
    path?: never;
    query?: {
        email?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/users/search';
};

export type SearchUsersResponses = {
    /**
     * OK
     */
    200: PageUserResponse;
};

export type SearchUsersResponse = SearchUsersResponses[keyof SearchUsersResponses];

export type SearchTablesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/tables/search';
};

export type SearchTablesResponses = {
    /**
     * OK
     */
    200: PageRestaurantTableResponse;
};

export type SearchTablesResponse = SearchTablesResponses[keyof SearchTablesResponses];

export type SearchSuppliersData = {
    body?: never;
    path?: never;
    query?: {
        nombre?: string;
        estado?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/suppliers/search';
};

export type SearchSuppliersResponses = {
    /**
     * OK
     */
    200: PageSupplierResponse;
};

export type SearchSuppliersResponse = SearchSuppliersResponses[keyof SearchSuppliersResponses];

export type GetSaleByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/sales/{id}';
};

export type GetSaleByIdResponses = {
    /**
     * OK
     */
    200: SaleResponse;
};

export type GetSaleByIdResponse = GetSaleByIdResponses[keyof GetSaleByIdResponses];

export type GetLatestSalesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/sales/latest';
};

export type GetLatestSalesResponses = {
    /**
     * OK
     */
    200: Array<SaleSummaryDto>;
};

export type GetLatestSalesResponse = GetLatestSalesResponses[keyof GetLatestSalesResponses];

export type GetTopProductsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/products/top';
};

export type GetTopProductsResponses = {
    /**
     * OK
     */
    200: Array<ProductTopDto>;
};

export type GetTopProductsResponse = GetTopProductsResponses[keyof GetTopProductsResponses];

export type SearchProductsData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/products/search';
};

export type SearchProductsResponses = {
    /**
     * OK
     */
    200: PageProductResponse;
};

export type SearchProductsResponse = SearchProductsResponses[keyof SearchProductsResponses];

export type GetProductsByCategoryData = {
    body?: never;
    path: {
        categoryId: number;
    };
    query?: never;
    url: '/api/products/category/{categoryId}';
};

export type GetProductsByCategoryResponses = {
    /**
     * OK
     */
    200: Array<ProductResponse>;
};

export type GetProductsByCategoryResponse = GetProductsByCategoryResponses[keyof GetProductsByCategoryResponses];

export type SearchProductsInventoryData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/products-inventory/search';
};

export type SearchProductsInventoryResponses = {
    /**
     * OK
     */
    200: PageProductInventoryResponse;
};

export type SearchProductsInventoryResponse = SearchProductsInventoryResponses[keyof SearchProductsInventoryResponses];

export type GetProductsInventoryByCategoryData = {
    body?: never;
    path: {
        categoryId: number;
    };
    query?: never;
    url: '/api/products-inventory/category/{categoryId}';
};

export type GetProductsInventoryByCategoryResponses = {
    /**
     * OK
     */
    200: Array<ProductInventoryResponse>;
};

export type GetProductsInventoryByCategoryResponse = GetProductsInventoryByCategoryResponses[keyof GetProductsInventoryByCategoryResponses];

export type GetOrderByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/orders/{id}';
};

export type GetOrderByIdResponses = {
    /**
     * OK
     */
    200: OrderResponse;
};

export type GetOrderByIdResponse = GetOrderByIdResponses[keyof GetOrderByIdResponses];

export type GetDeliveryOrdersData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
    };
    url: '/api/orders/delivery';
};

export type GetDeliveryOrdersResponses = {
    /**
     * OK
     */
    200: Array<OrderDeliveryDto>;
};

export type GetDeliveryOrdersResponse = GetDeliveryOrdersResponses[keyof GetDeliveryOrdersResponses];

export type GetMovementByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/inventory-movements/{id}';
};

export type GetMovementByIdResponses = {
    /**
     * OK
     */
    200: MovementInventoryResponse;
};

export type GetMovementByIdResponse = GetMovementByIdResponses[keyof GetMovementByIdResponses];

export type SearchEmployeesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/employees/search';
};

export type SearchEmployeesResponses = {
    /**
     * OK
     */
    200: PageEmployeeResponse;
};

export type SearchEmployeesResponse = SearchEmployeesResponses[keyof SearchEmployeesResponses];

export type GetSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/summary';
};

export type GetSummaryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses];

export type GetLatestSales1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dashboard/latest-sales';
};

export type GetLatestSales1Responses = {
    /**
     * OK
     */
    200: Array<SaleResponse>;
};

export type GetLatestSales1Response = GetLatestSales1Responses[keyof GetLatestSales1Responses];

export type SearchCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/categories/search';
};

export type SearchCategoriesResponses = {
    /**
     * OK
     */
    200: PageCategoryResponse;
};

export type SearchCategoriesResponse = SearchCategoriesResponses[keyof SearchCategoriesResponses];

export type SearchCategoriesInventoryData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        status?: boolean;
        page?: number;
        size?: number;
    };
    url: '/api/categories-inventory/search';
};

export type SearchCategoriesInventoryResponses = {
    /**
     * OK
     */
    200: PageCategoryInventoryResponse;
};

export type SearchCategoriesInventoryResponse = SearchCategoriesInventoryResponses[keyof SearchCategoriesInventoryResponses];

export type GetCashBoxByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cashboxes/{id}';
};

export type GetCashBoxByIdResponses = {
    /**
     * OK
     */
    200: CashBoxResponse;
};

export type GetCashBoxByIdResponse = GetCashBoxByIdResponses[keyof GetCashBoxByIdResponses];

export type GetMovements1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/cashboxes/{id}/movements';
};

export type GetMovements1Responses = {
    /**
     * OK
     */
    200: PageMovementCashboxResponse;
};

export type GetMovements1Response = GetMovements1Responses[keyof GetMovements1Responses];
